[[plugins]]
package = "/plugins/aggregate-data"
    [plugins.inputs]
      # Where should data files reside
      dataDir = "_data"

[[plugins]]
package = "/plugins/webp-handler"
    [plugins.inputs]
      # Where should data files reside
      dataDir = "assets/img/uploads"
      ttl = 2592000
